# Generated by Django 6.0.6 on 2026-06-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='account_level',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_note',
            field=models.CharField(blank=True, default='Direct WhatsApp handover after payment confirmation.', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='server',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement',
            field=models.CharField(blank=True, default='Fresh accounts are reviewed and updated regularly.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='store_name',
            field=models.CharField(default='Gameslot', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_number',
            field=models.CharField(default='60102431634', max_length=24),
        ),
    ]
