# Generated by Django 6.0.6 on 2026-06-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0003_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='accent_color',
            field=models.CharField(blank=True, default='#ff8ebb', max_length=24),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_note',
            field=models.CharField(blank=True, default='Ready stock', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='support_hours',
            field=models.CharField(blank=True, default='Daily support', max_length=80),
        ),
    ]
